#!/bin/sh

function cfo() {
    if [ $? != 0 ]; then
        echo "-- Error on $1"
        exit $?
    else
        echo "++ Success on $1"    
    fi    
}

ID=xinf-core
NAMESPACES=xinf

if [ -e $ID.zip ]; then 
	rm $ID.zip
	cfo "removing previous zip package"
fi

if [ -e $ID ]; then	
	rm -R $ID
	cfo "removing previous package source tree"
fi

#root
mkdir $ID
cfo "creating source tree folder"
cp haxelib.xml $ID
cfo "copying haxelib xml config"


for NS in $NAMESPACES; do
	svn export api/$NS $ID/$NS
	cfo "exporting sources in $NS from local SVN checkout"
done

svn export samples/ $ID/samples/
cfo "exporting samples from local SVN checkout"

zip -r $ID.zip $ID
cfo "zipping package $ID.zip"
