extern class GL {
	public static var VERSION_1_1:Int;
	public static var VERSION_1_2:Int;
	public static var VERSION_1_3:Int;
	public static var ARB_imaging:Int;
	public static var FALSE:Int;
	public static var TRUE:Int;
	public static var BYTE:Int;
	public static var UNSIGNED_BYTE:Int;
	public static var SHORT:Int;
	public static var UNSIGNED_SHORT:Int;
	public static var INT:Int;
	public static var UNSIGNED_INT:Int;
	public static var FLOAT:Int;
	public static var n_2_BYTES:Int;
	public static var n_3_BYTES:Int;
	public static var n_4_BYTES:Int;
	public static var DOUBLE:Int;
	public static var POINTS:Int;
	public static var LINES:Int;
	public static var LINE_LOOP:Int;
	public static var LINE_STRIP:Int;
	public static var TRIANGLES:Int;
	public static var TRIANGLE_STRIP:Int;
	public static var TRIANGLE_FAN:Int;
	public static var QUADS:Int;
	public static var QUAD_STRIP:Int;
	public static var POLYGON:Int;
	public static var VERTEX_ARRAY:Int;
	public static var NORMAL_ARRAY:Int;
	public static var COLOR_ARRAY:Int;
	public static var INDEX_ARRAY:Int;
	public static var TEXTURE_COORD_ARRAY:Int;
	public static var EDGE_FLAG_ARRAY:Int;
	public static var VERTEX_ARRAY_SIZE:Int;
	public static var VERTEX_ARRAY_TYPE:Int;
	public static var VERTEX_ARRAY_STRIDE:Int;
	public static var NORMAL_ARRAY_TYPE:Int;
	public static var NORMAL_ARRAY_STRIDE:Int;
	public static var COLOR_ARRAY_SIZE:Int;
	public static var COLOR_ARRAY_TYPE:Int;
	public static var COLOR_ARRAY_STRIDE:Int;
	public static var INDEX_ARRAY_TYPE:Int;
	public static var INDEX_ARRAY_STRIDE:Int;
	public static var TEXTURE_COORD_ARRAY_SIZE:Int;
	public static var TEXTURE_COORD_ARRAY_TYPE:Int;
	public static var TEXTURE_COORD_ARRAY_STRIDE:Int;
	public static var EDGE_FLAG_ARRAY_STRIDE:Int;
	public static var VERTEX_ARRAY_POINTER:Int;
	public static var NORMAL_ARRAY_POINTER:Int;
	public static var COLOR_ARRAY_POINTER:Int;
	public static var INDEX_ARRAY_POINTER:Int;
	public static var TEXTURE_COORD_ARRAY_POINTER:Int;
	public static var EDGE_FLAG_ARRAY_POINTER:Int;
	public static var V2F:Int;
	public static var V3F:Int;
	public static var C4UB_V2F:Int;
	public static var C4UB_V3F:Int;
	public static var C3F_V3F:Int;
	public static var N3F_V3F:Int;
	public static var C4F_N3F_V3F:Int;
	public static var T2F_V3F:Int;
	public static var T4F_V4F:Int;
	public static var T2F_C4UB_V3F:Int;
	public static var T2F_C3F_V3F:Int;
	public static var T2F_N3F_V3F:Int;
	public static var T2F_C4F_N3F_V3F:Int;
	public static var T4F_C4F_N3F_V4F:Int;
	public static var MATRIX_MODE:Int;
	public static var MODELVIEW:Int;
	public static var PROJECTION:Int;
	public static var TEXTURE:Int;
	public static var POINT_SMOOTH:Int;
	public static var POINT_SIZE:Int;
	public static var POINT_SIZE_GRANULARITY:Int;
	public static var POINT_SIZE_RANGE:Int;
	public static var LINE_SMOOTH:Int;
	public static var LINE_STIPPLE:Int;
	public static var LINE_STIPPLE_PATTERN:Int;
	public static var LINE_STIPPLE_REPEAT:Int;
	public static var LINE_WIDTH:Int;
	public static var LINE_WIDTH_GRANULARITY:Int;
	public static var LINE_WIDTH_RANGE:Int;
	public static var POINT:Int;
	public static var LINE:Int;
	public static var FILL:Int;
	public static var CW:Int;
	public static var CCW:Int;
	public static var FRONT:Int;
	public static var BACK:Int;
	public static var POLYGON_MODE:Int;
	public static var POLYGON_SMOOTH:Int;
	public static var POLYGON_STIPPLE:Int;
	public static var EDGE_FLAG:Int;
	public static var CULL_FACE:Int;
	public static var CULL_FACE_MODE:Int;
	public static var FRONT_FACE:Int;
	public static var POLYGON_OFFSET_FACTOR:Int;
	public static var POLYGON_OFFSET_UNITS:Int;
	public static var POLYGON_OFFSET_POINT:Int;
	public static var POLYGON_OFFSET_LINE:Int;
	public static var POLYGON_OFFSET_FILL:Int;
	public static var COMPILE:Int;
	public static var COMPILE_AND_EXECUTE:Int;
	public static var LIST_BASE:Int;
	public static var LIST_INDEX:Int;
	public static var LIST_MODE:Int;
	public static var NEVER:Int;
	public static var LESS:Int;
	public static var EQUAL:Int;
	public static var LEQUAL:Int;
	public static var GREATER:Int;
	public static var NOTEQUAL:Int;
	public static var GEQUAL:Int;
	public static var ALWAYS:Int;
	public static var DEPTH_TEST:Int;
	public static var DEPTH_BITS:Int;
	public static var DEPTH_CLEAR_VALUE:Int;
	public static var DEPTH_FUNC:Int;
	public static var DEPTH_RANGE:Int;
	public static var DEPTH_WRITEMASK:Int;
	public static var DEPTH_COMPONENT:Int;
	public static var LIGHTING:Int;
	public static var LIGHT0:Int;
	public static var LIGHT1:Int;
	public static var LIGHT2:Int;
	public static var LIGHT3:Int;
	public static var LIGHT4:Int;
	public static var LIGHT5:Int;
	public static var LIGHT6:Int;
	public static var LIGHT7:Int;
	public static var SPOT_EXPONENT:Int;
	public static var SPOT_CUTOFF:Int;
	public static var CONSTANT_ATTENUATION:Int;
	public static var LINEAR_ATTENUATION:Int;
	public static var QUADRATIC_ATTENUATION:Int;
	public static var AMBIENT:Int;
	public static var DIFFUSE:Int;
	public static var SPECULAR:Int;
	public static var SHININESS:Int;
	public static var EMISSION:Int;
	public static var POSITION:Int;
	public static var SPOT_DIRECTION:Int;
	public static var AMBIENT_AND_DIFFUSE:Int;
	public static var COLOR_INDEXES:Int;
	public static var LIGHT_MODEL_TWO_SIDE:Int;
	public static var LIGHT_MODEL_LOCAL_VIEWER:Int;
	public static var LIGHT_MODEL_AMBIENT:Int;
	public static var FRONT_AND_BACK:Int;
	public static var SHADE_MODEL:Int;
	public static var FLAT:Int;
	public static var SMOOTH:Int;
	public static var COLOR_MATERIAL:Int;
	public static var COLOR_MATERIAL_FACE:Int;
	public static var COLOR_MATERIAL_PARAMETER:Int;
	public static var NORMALIZE:Int;
	public static var CLIP_PLANE0:Int;
	public static var CLIP_PLANE1:Int;
	public static var CLIP_PLANE2:Int;
	public static var CLIP_PLANE3:Int;
	public static var CLIP_PLANE4:Int;
	public static var CLIP_PLANE5:Int;
	public static var ACCUM_RED_BITS:Int;
	public static var ACCUM_GREEN_BITS:Int;
	public static var ACCUM_BLUE_BITS:Int;
	public static var ACCUM_ALPHA_BITS:Int;
	public static var ACCUM_CLEAR_VALUE:Int;
	public static var ACCUM:Int;
	public static var ADD:Int;
	public static var LOAD:Int;
	public static var MULT:Int;
	public static var RETURN:Int;
	public static var ALPHA_TEST:Int;
	public static var ALPHA_TEST_REF:Int;
	public static var ALPHA_TEST_FUNC:Int;
	public static var BLEND:Int;
	public static var BLEND_SRC:Int;
	public static var BLEND_DST:Int;
	public static var ZERO:Int;
	public static var ONE:Int;
	public static var SRC_COLOR:Int;
	public static var ONE_MINUS_SRC_COLOR:Int;
	public static var SRC_ALPHA:Int;
	public static var ONE_MINUS_SRC_ALPHA:Int;
	public static var DST_ALPHA:Int;
	public static var ONE_MINUS_DST_ALPHA:Int;
	public static var DST_COLOR:Int;
	public static var ONE_MINUS_DST_COLOR:Int;
	public static var SRC_ALPHA_SATURATE:Int;
	public static var FEEDBACK:Int;
	public static var RENDER:Int;
	public static var SELECT:Int;
	public static var n_2D:Int;
	public static var n_3D:Int;
	public static var n_3D_COLOR:Int;
	public static var n_3D_COLOR_TEXTURE:Int;
	public static var n_4D_COLOR_TEXTURE:Int;
	public static var POINT_TOKEN:Int;
	public static var LINE_TOKEN:Int;
	public static var LINE_RESET_TOKEN:Int;
	public static var POLYGON_TOKEN:Int;
	public static var BITMAP_TOKEN:Int;
	public static var DRAW_PIXEL_TOKEN:Int;
	public static var COPY_PIXEL_TOKEN:Int;
	public static var PASS_THROUGH_TOKEN:Int;
	public static var FEEDBACK_BUFFER_POINTER:Int;
	public static var FEEDBACK_BUFFER_SIZE:Int;
	public static var FEEDBACK_BUFFER_TYPE:Int;
	public static var SELECTION_BUFFER_POINTER:Int;
	public static var SELECTION_BUFFER_SIZE:Int;
	public static var FOG:Int;
	public static var FOG_MODE:Int;
	public static var FOG_DENSITY:Int;
	public static var FOG_COLOR:Int;
	public static var FOG_INDEX:Int;
	public static var FOG_START:Int;
	public static var FOG_END:Int;
	public static var LINEAR:Int;
	public static var EXP:Int;
	public static var EXP2:Int;
	public static var LOGIC_OP:Int;
	public static var INDEX_LOGIC_OP:Int;
	public static var COLOR_LOGIC_OP:Int;
	public static var LOGIC_OP_MODE:Int;
	public static var CLEAR:Int;
	public static var SET:Int;
	public static var COPY:Int;
	public static var COPY_INVERTED:Int;
	public static var NOOP:Int;
	public static var INVERT:Int;
	public static var AND:Int;
	public static var NAND:Int;
	public static var OR:Int;
	public static var NOR:Int;
	public static var XOR:Int;
	public static var EQUIV:Int;
	public static var AND_REVERSE:Int;
	public static var AND_INVERTED:Int;
	public static var OR_REVERSE:Int;
	public static var OR_INVERTED:Int;
	public static var STENCIL_TEST:Int;
	public static var STENCIL_WRITEMASK:Int;
	public static var STENCIL_BITS:Int;
	public static var STENCIL_FUNC:Int;
	public static var STENCIL_VALUE_MASK:Int;
	public static var STENCIL_REF:Int;
	public static var STENCIL_FAIL:Int;
	public static var STENCIL_PASS_DEPTH_PASS:Int;
	public static var STENCIL_PASS_DEPTH_FAIL:Int;
	public static var STENCIL_CLEAR_VALUE:Int;
	public static var STENCIL_INDEX:Int;
	public static var KEEP:Int;
	public static var REPLACE:Int;
	public static var INCR:Int;
	public static var DECR:Int;
	public static var NONE:Int;
	public static var LEFT:Int;
	public static var RIGHT:Int;
	public static var FRONT_LEFT:Int;
	public static var FRONT_RIGHT:Int;
	public static var BACK_LEFT:Int;
	public static var BACK_RIGHT:Int;
	public static var AUX0:Int;
	public static var AUX1:Int;
	public static var AUX2:Int;
	public static var AUX3:Int;
	public static var COLOR_INDEX:Int;
	public static var RED:Int;
	public static var GREEN:Int;
	public static var BLUE:Int;
	public static var ALPHA:Int;
	public static var LUMINANCE:Int;
	public static var LUMINANCE_ALPHA:Int;
	public static var ALPHA_BITS:Int;
	public static var RED_BITS:Int;
	public static var GREEN_BITS:Int;
	public static var BLUE_BITS:Int;
	public static var INDEX_BITS:Int;
	public static var SUBPIXEL_BITS:Int;
	public static var AUX_BUFFERS:Int;
	public static var READ_BUFFER:Int;
	public static var DRAW_BUFFER:Int;
	public static var DOUBLEBUFFER:Int;
	public static var STEREO:Int;
	public static var BITMAP:Int;
	public static var COLOR:Int;
	public static var DEPTH:Int;
	public static var STENCIL:Int;
	public static var DITHER:Int;
	public static var RGB:Int;
	public static var RGBA:Int;
	public static var MAX_LIST_NESTING:Int;
	public static var MAX_ATTRIB_STACK_DEPTH:Int;
	public static var MAX_MODELVIEW_STACK_DEPTH:Int;
	public static var MAX_NAME_STACK_DEPTH:Int;
	public static var MAX_PROJECTION_STACK_DEPTH:Int;
	public static var MAX_TEXTURE_STACK_DEPTH:Int;
	public static var MAX_EVAL_ORDER:Int;
	public static var MAX_LIGHTS:Int;
	public static var MAX_CLIP_PLANES:Int;
	public static var MAX_TEXTURE_SIZE:Int;
	public static var MAX_PIXEL_MAP_TABLE:Int;
	public static var MAX_VIEWPORT_DIMS:Int;
	public static var MAX_CLIENT_ATTRIB_STACK_DEPTH:Int;
	public static var ATTRIB_STACK_DEPTH:Int;
	public static var CLIENT_ATTRIB_STACK_DEPTH:Int;
	public static var COLOR_CLEAR_VALUE:Int;
	public static var COLOR_WRITEMASK:Int;
	public static var CURRENT_INDEX:Int;
	public static var CURRENT_COLOR:Int;
	public static var CURRENT_NORMAL:Int;
	public static var CURRENT_RASTER_COLOR:Int;
	public static var CURRENT_RASTER_DISTANCE:Int;
	public static var CURRENT_RASTER_INDEX:Int;
	public static var CURRENT_RASTER_POSITION:Int;
	public static var CURRENT_RASTER_TEXTURE_COORDS:Int;
	public static var CURRENT_RASTER_POSITION_VALID:Int;
	public static var CURRENT_TEXTURE_COORDS:Int;
	public static var INDEX_CLEAR_VALUE:Int;
	public static var INDEX_MODE:Int;
	public static var INDEX_WRITEMASK:Int;
	public static var MODELVIEW_MATRIX:Int;
	public static var MODELVIEW_STACK_DEPTH:Int;
	public static var NAME_STACK_DEPTH:Int;
	public static var PROJECTION_MATRIX:Int;
	public static var PROJECTION_STACK_DEPTH:Int;
	public static var RENDER_MODE:Int;
	public static var RGBA_MODE:Int;
	public static var TEXTURE_MATRIX:Int;
	public static var TEXTURE_STACK_DEPTH:Int;
	public static var VIEWPORT:Int;
	public static var AUTO_NORMAL:Int;
	public static var MAP1_COLOR_4:Int;
	public static var MAP1_INDEX:Int;
	public static var MAP1_NORMAL:Int;
	public static var MAP1_TEXTURE_COORD_1:Int;
	public static var MAP1_TEXTURE_COORD_2:Int;
	public static var MAP1_TEXTURE_COORD_3:Int;
	public static var MAP1_TEXTURE_COORD_4:Int;
	public static var MAP1_VERTEX_3:Int;
	public static var MAP1_VERTEX_4:Int;
	public static var MAP2_COLOR_4:Int;
	public static var MAP2_INDEX:Int;
	public static var MAP2_NORMAL:Int;
	public static var MAP2_TEXTURE_COORD_1:Int;
	public static var MAP2_TEXTURE_COORD_2:Int;
	public static var MAP2_TEXTURE_COORD_3:Int;
	public static var MAP2_TEXTURE_COORD_4:Int;
	public static var MAP2_VERTEX_3:Int;
	public static var MAP2_VERTEX_4:Int;
	public static var MAP1_GRID_DOMAIN:Int;
	public static var MAP1_GRID_SEGMENTS:Int;
	public static var MAP2_GRID_DOMAIN:Int;
	public static var MAP2_GRID_SEGMENTS:Int;
	public static var COEFF:Int;
	public static var DOMAIN:Int;
	public static var ORDER:Int;
	public static var FOG_HINT:Int;
	public static var LINE_SMOOTH_HINT:Int;
	public static var PERSPECTIVE_CORRECTION_HINT:Int;
	public static var POINT_SMOOTH_HINT:Int;
	public static var POLYGON_SMOOTH_HINT:Int;
	public static var DONT_CARE:Int;
	public static var FASTEST:Int;
	public static var NICEST:Int;
	public static var SCISSOR_TEST:Int;
	public static var SCISSOR_BOX:Int;
	public static var MAP_COLOR:Int;
	public static var MAP_STENCIL:Int;
	public static var INDEX_SHIFT:Int;
	public static var INDEX_OFFSET:Int;
	public static var RED_SCALE:Int;
	public static var RED_BIAS:Int;
	public static var GREEN_SCALE:Int;
	public static var GREEN_BIAS:Int;
	public static var BLUE_SCALE:Int;
	public static var BLUE_BIAS:Int;
	public static var ALPHA_SCALE:Int;
	public static var ALPHA_BIAS:Int;
	public static var DEPTH_SCALE:Int;
	public static var DEPTH_BIAS:Int;
	public static var PIXEL_MAP_S_TO_S_SIZE:Int;
	public static var PIXEL_MAP_I_TO_I_SIZE:Int;
	public static var PIXEL_MAP_I_TO_R_SIZE:Int;
	public static var PIXEL_MAP_I_TO_G_SIZE:Int;
	public static var PIXEL_MAP_I_TO_B_SIZE:Int;
	public static var PIXEL_MAP_I_TO_A_SIZE:Int;
	public static var PIXEL_MAP_R_TO_R_SIZE:Int;
	public static var PIXEL_MAP_G_TO_G_SIZE:Int;
	public static var PIXEL_MAP_B_TO_B_SIZE:Int;
	public static var PIXEL_MAP_A_TO_A_SIZE:Int;
	public static var PIXEL_MAP_S_TO_S:Int;
	public static var PIXEL_MAP_I_TO_I:Int;
	public static var PIXEL_MAP_I_TO_R:Int;
	public static var PIXEL_MAP_I_TO_G:Int;
	public static var PIXEL_MAP_I_TO_B:Int;
	public static var PIXEL_MAP_I_TO_A:Int;
	public static var PIXEL_MAP_R_TO_R:Int;
	public static var PIXEL_MAP_G_TO_G:Int;
	public static var PIXEL_MAP_B_TO_B:Int;
	public static var PIXEL_MAP_A_TO_A:Int;
	public static var PACK_ALIGNMENT:Int;
	public static var PACK_LSB_FIRST:Int;
	public static var PACK_ROW_LENGTH:Int;
	public static var PACK_SKIP_PIXELS:Int;
	public static var PACK_SKIP_ROWS:Int;
	public static var PACK_SWAP_BYTES:Int;
	public static var UNPACK_ALIGNMENT:Int;
	public static var UNPACK_LSB_FIRST:Int;
	public static var UNPACK_ROW_LENGTH:Int;
	public static var UNPACK_SKIP_PIXELS:Int;
	public static var UNPACK_SKIP_ROWS:Int;
	public static var UNPACK_SWAP_BYTES:Int;
	public static var ZOOM_X:Int;
	public static var ZOOM_Y:Int;
	public static var TEXTURE_ENV:Int;
	public static var TEXTURE_ENV_MODE:Int;
	public static var TEXTURE_1D:Int;
	public static var TEXTURE_2D:Int;
	public static var TEXTURE_WRAP_S:Int;
	public static var TEXTURE_WRAP_T:Int;
	public static var TEXTURE_MAG_FILTER:Int;
	public static var TEXTURE_MIN_FILTER:Int;
	public static var TEXTURE_ENV_COLOR:Int;
	public static var TEXTURE_GEN_S:Int;
	public static var TEXTURE_GEN_T:Int;
	public static var TEXTURE_GEN_MODE:Int;
	public static var TEXTURE_BORDER_COLOR:Int;
	public static var TEXTURE_WIDTH:Int;
	public static var TEXTURE_HEIGHT:Int;
	public static var TEXTURE_BORDER:Int;
	public static var TEXTURE_COMPONENTS:Int;
	public static var TEXTURE_RED_SIZE:Int;
	public static var TEXTURE_GREEN_SIZE:Int;
	public static var TEXTURE_BLUE_SIZE:Int;
	public static var TEXTURE_ALPHA_SIZE:Int;
	public static var TEXTURE_LUMINANCE_SIZE:Int;
	public static var TEXTURE_INTENSITY_SIZE:Int;
	public static var NEAREST_MIPMAP_NEAREST:Int;
	public static var NEAREST_MIPMAP_LINEAR:Int;
	public static var LINEAR_MIPMAP_NEAREST:Int;
	public static var LINEAR_MIPMAP_LINEAR:Int;
	public static var OBJECT_LINEAR:Int;
	public static var OBJECT_PLANE:Int;
	public static var EYE_LINEAR:Int;
	public static var EYE_PLANE:Int;
	public static var SPHERE_MAP:Int;
	public static var DECAL:Int;
	public static var MODULATE:Int;
	public static var NEAREST:Int;
	public static var REPEAT:Int;
	public static var CLAMP:Int;
	public static var S:Int;
	public static var T:Int;
	public static var R:Int;
	public static var Q:Int;
	public static var TEXTURE_GEN_R:Int;
	public static var TEXTURE_GEN_Q:Int;
	public static var VENDOR:Int;
	public static var RENDERER:Int;
	public static var VERSION:Int;
	public static var EXTENSIONS:Int;
	public static var NO_ERROR:Int;
	public static var INVALID_VALUE:Int;
	public static var INVALID_ENUM:Int;
	public static var INVALID_OPERATION:Int;
	public static var STACK_OVERFLOW:Int;
	public static var STACK_UNDERFLOW:Int;
	public static var OUT_OF_MEMORY:Int;
	public static var CURRENT_BIT:Int;
	public static var POINT_BIT:Int;
	public static var LINE_BIT:Int;
	public static var POLYGON_BIT:Int;
	public static var POLYGON_STIPPLE_BIT:Int;
	public static var PIXEL_MODE_BIT:Int;
	public static var LIGHTING_BIT:Int;
	public static var FOG_BIT:Int;
	public static var DEPTH_BUFFER_BIT:Int;
	public static var ACCUM_BUFFER_BIT:Int;
	public static var STENCIL_BUFFER_BIT:Int;
	public static var VIEWPORT_BIT:Int;
	public static var TRANSFORM_BIT:Int;
	public static var ENABLE_BIT:Int;
	public static var COLOR_BUFFER_BIT:Int;
	public static var HINT_BIT:Int;
	public static var EVAL_BIT:Int;
	public static var LIST_BIT:Int;
	public static var TEXTURE_BIT:Int;
	public static var SCISSOR_BIT:Int;
	public static var ALL_ATTRIB_BITS:Int;
	public static var PROXY_TEXTURE_1D:Int;
	public static var PROXY_TEXTURE_2D:Int;
	public static var TEXTURE_PRIORITY:Int;
	public static var TEXTURE_RESIDENT:Int;
	public static var TEXTURE_BINDING_1D:Int;
	public static var TEXTURE_BINDING_2D:Int;
	public static var TEXTURE_INTERNAL_FORMAT:Int;
	public static var ALPHA4:Int;
	public static var ALPHA8:Int;
	public static var ALPHA12:Int;
	public static var ALPHA16:Int;
	public static var LUMINANCE4:Int;
	public static var LUMINANCE8:Int;
	public static var LUMINANCE12:Int;
	public static var LUMINANCE16:Int;
	public static var LUMINANCE4_ALPHA4:Int;
	public static var LUMINANCE6_ALPHA2:Int;
	public static var LUMINANCE8_ALPHA8:Int;
	public static var LUMINANCE12_ALPHA4:Int;
	public static var LUMINANCE12_ALPHA12:Int;
	public static var LUMINANCE16_ALPHA16:Int;
	public static var INTENSITY:Int;
	public static var INTENSITY4:Int;
	public static var INTENSITY8:Int;
	public static var INTENSITY12:Int;
	public static var INTENSITY16:Int;
	public static var R3_G3_B2:Int;
	public static var RGB4:Int;
	public static var RGB5:Int;
	public static var RGB8:Int;
	public static var RGB10:Int;
	public static var RGB12:Int;
	public static var RGB16:Int;
	public static var RGBA2:Int;
	public static var RGBA4:Int;
	public static var RGB5_A1:Int;
	public static var RGBA8:Int;
	public static var RGB10_A2:Int;
	public static var RGBA12:Int;
	public static var RGBA16:Int;
	public static var CLIENT_PIXEL_STORE_BIT:Int;
	public static var CLIENT_VERTEX_ARRAY_BIT:Int;
	public static var ALL_CLIENT_ATTRIB_BITS:Int;
	public static var CLIENT_ALL_ATTRIB_BITS:Int;
	public static function ClearIndex( _c:Float ):Void;
	public static function ClearColor( _red:Float, _green:Float, _blue:Float, _alpha:Float ):Void;
	public static function Clear( _mask:Int ):Void;
	public static function IndexMask( _mask:Int ):Void;
	public static function ColorMask( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function AlphaFunc( _func:Int, _ref:Float ):Void;
	public static function BlendFunc( _sfactor:Int, _dfactor:Int ):Void;
	public static function LogicOp( _opcode:Int ):Void;
	public static function CullFace( _mode:Int ):Void;
	public static function FrontFace( _mode:Int ):Void;
	public static function PointSize( _size:Float ):Void;
	public static function LineWidth( _width:Float ):Void;
	public static function LineStipple( _factor:Int, _pattern:Int ):Void;
	public static function PolygonMode( _face:Int, _mode:Int ):Void;
	public static function PolygonOffset( _factor:Float, _units:Float ):Void;
	public static function PolygonStipple( _mask:String ):Void;
	public static function GetPolygonStipple( _mask:String ):Void;
	public static function EdgeFlag( _flag:Int ):Void;
	public static function EdgeFlagv( _flag:String ):Void;
	public static function Scissor( _x:Int, _y:Int, _width:Int, _height:Int ):Void;
	public static function ClipPlane( _plane:Int, _equation:Float ):Void;
	public static function GetClipPlane( _plane:Int, _equation:Float ):Void;
	public static function DrawBuffer( _mode:Int ):Void;
	public static function ReadBuffer( _mode:Int ):Void;
	public static function Enable( _cap:Int ):Void;
	public static function Disable( _cap:Int ):Void;
	public static function IsEnabled( _cap:Int ):Int;
	public static function EnableClientState( _cap:Int ):Void;
	public static function DisableClientState( _cap:Int ):Void;
	public static function GetBooleanv( _pname:Int, _params:String ):Void;
	public static function GetDoublev( _pname:Int, _params:Float ):Void;
	public static function GetFloatv( _pname:Int, _params:Float ):Void;
	public static function GetIntegerv( _pname:Int, _params:Int ):Void;
	public static function PushAttrib( _mask:Int ):Void;
	public static function PopAttrib( ):Void;
	public static function PushClientAttrib( _mask:Int ):Void;
	public static function PopClientAttrib( ):Void;
	public static function RenderMode( _mode:Int ):Int;
	public static function GetError( ):Int;
	public static function GetString( _name:Int ):String;
	public static function Finish( ):Void;
	public static function Flush( ):Void;
	public static function Hint( _target:Int, _mode:Int ):Void;
	public static function ClearDepth( _depth:Float ):Void;
	public static function DepthFunc( _func:Int ):Void;
	public static function DepthMask( _flag:Int ):Void;
	public static function DepthRange( _near_val:Float, _far_val:Float ):Void;
	public static function ClearAccum( _red:Float, _green:Float, _blue:Float, _alpha:Float ):Void;
	public static function Accum( _op:Int, _value:Float ):Void;
	public static function MatrixMode( _mode:Int ):Void;
	public static function Ortho( _left:Float, _right:Float, _bottom:Float, _top:Float, _near_val:Float, _far_val:Float ):Void;
	public static function Frustum( _left:Float, _right:Float, _bottom:Float, _top:Float, _near_val:Float, _far_val:Float ):Void;
	public static function Viewport( _x:Int, _y:Int, _width:Int, _height:Int ):Void;
	public static function PushMatrix( ):Void;
	public static function PopMatrix( ):Void;
	public static function LoadIdentity( ):Void;
	public static function LoadMatrixd( _m:Float ):Void;
	public static function LoadMatrixf( _m:Float ):Void;
	public static function MultMatrixd( _m:Float ):Void;
	public static function MultMatrixf( _m:Float ):Void;
	public static function Rotated( _angle:Float, _x:Float, _y:Float, _z:Float ):Void;
	public static function Rotatef( _angle:Float, _x:Float, _y:Float, _z:Float ):Void;
	public static function Scaled( _x:Float, _y:Float, _z:Float ):Void;
	public static function Scalef( _x:Float, _y:Float, _z:Float ):Void;
	public static function Translated( _x:Float, _y:Float, _z:Float ):Void;
	public static function Translatef( _x:Float, _y:Float, _z:Float ):Void;
	public static function IsList( _list:Int ):Int;
	public static function DeleteLists( _list:Int, _range:Int ):Void;
	public static function GenLists( _range:Int ):Int;
	public static function NewList( _list:Int, _mode:Int ):Void;
	public static function EndList( ):Void;
	public static function CallList( _list:Int ):Void;
	public static function CallLists( _n:Int, _type:Int, _lists:Void ):Void;
	public static function ListBase( _base:Int ):Void;
	public static function Begin( _mode:Int ):Void;
	public static function End( ):Void;
	public static function Vertex2d( _x:Float, _y:Float ):Void;
	public static function Vertex2f( _x:Float, _y:Float ):Void;
	public static function Vertex2i( _x:Int, _y:Int ):Void;
	public static function Vertex2s( _x:Int, _y:Int ):Void;
	public static function Vertex3d( _x:Float, _y:Float, _z:Float ):Void;
	public static function Vertex3f( _x:Float, _y:Float, _z:Float ):Void;
	public static function Vertex3i( _x:Int, _y:Int, _z:Int ):Void;
	public static function Vertex3s( _x:Int, _y:Int, _z:Int ):Void;
	public static function Vertex4d( _x:Float, _y:Float, _z:Float, _w:Float ):Void;
	public static function Vertex4f( _x:Float, _y:Float, _z:Float, _w:Float ):Void;
	public static function Vertex4i( _x:Int, _y:Int, _z:Int, _w:Int ):Void;
	public static function Vertex4s( _x:Int, _y:Int, _z:Int, _w:Int ):Void;
	public static function Vertex2dv( _v:Float ):Void;
	public static function Vertex2fv( _v:Float ):Void;
	public static function Vertex2iv( _v:Int ):Void;
	public static function Vertex2sv( _v:Int ):Void;
	public static function Vertex3dv( _v:Float ):Void;
	public static function Vertex3fv( _v:Float ):Void;
	public static function Vertex3iv( _v:Int ):Void;
	public static function Vertex3sv( _v:Int ):Void;
	public static function Vertex4dv( _v:Float ):Void;
	public static function Vertex4fv( _v:Float ):Void;
	public static function Vertex4iv( _v:Int ):Void;
	public static function Vertex4sv( _v:Int ):Void;
	public static function Normal3b( _nx:Int, _ny:Int, _nz:Int ):Void;
	public static function Normal3d( _nx:Float, _ny:Float, _nz:Float ):Void;
	public static function Normal3f( _nx:Float, _ny:Float, _nz:Float ):Void;
	public static function Normal3i( _nx:Int, _ny:Int, _nz:Int ):Void;
	public static function Normal3s( _nx:Int, _ny:Int, _nz:Int ):Void;
	public static function Normal3bv( _v:Int ):Void;
	public static function Normal3dv( _v:Float ):Void;
	public static function Normal3fv( _v:Float ):Void;
	public static function Normal3iv( _v:Int ):Void;
	public static function Normal3sv( _v:Int ):Void;
	public static function Indexd( _c:Float ):Void;
	public static function Indexf( _c:Float ):Void;
	public static function Indexi( _c:Int ):Void;
	public static function Indexs( _c:Int ):Void;
	public static function Indexub( _c:Int ):Void;
	public static function Indexdv( _c:Float ):Void;
	public static function Indexfv( _c:Float ):Void;
	public static function Indexiv( _c:Int ):Void;
	public static function Indexsv( _c:Int ):Void;
	public static function Indexubv( _c:String ):Void;
	public static function Color3b( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color3d( _red:Float, _green:Float, _blue:Float ):Void;
	public static function Color3f( _red:Float, _green:Float, _blue:Float ):Void;
	public static function Color3i( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color3s( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color3ub( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color3ui( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color3us( _red:Int, _green:Int, _blue:Int ):Void;
	public static function Color4b( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color4d( _red:Float, _green:Float, _blue:Float, _alpha:Float ):Void;
	public static function Color4f( _red:Float, _green:Float, _blue:Float, _alpha:Float ):Void;
	public static function Color4i( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color4s( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color4ub( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color4ui( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color4us( _red:Int, _green:Int, _blue:Int, _alpha:Int ):Void;
	public static function Color3bv( _v:Int ):Void;
	public static function Color3dv( _v:Float ):Void;
	public static function Color3fv( _v:Float ):Void;
	public static function Color3iv( _v:Int ):Void;
	public static function Color3sv( _v:Int ):Void;
	public static function Color3ubv( _v:String ):Void;
	public static function Color3uiv( _v:Int ):Void;
	public static function Color3usv( _v:Int ):Void;
	public static function Color4bv( _v:Int ):Void;
	public static function Color4dv( _v:Float ):Void;
	public static function Color4fv( _v:Float ):Void;
	public static function Color4iv( _v:Int ):Void;
	public static function Color4sv( _v:Int ):Void;
	public static function Color4ubv( _v:String ):Void;
	public static function Color4uiv( _v:Int ):Void;
	public static function Color4usv( _v:Int ):Void;
	public static function TexCoord1d( _s:Float ):Void;
	public static function TexCoord1f( _s:Float ):Void;
	public static function TexCoord1i( _s:Int ):Void;
	public static function TexCoord1s( _s:Int ):Void;
	public static function TexCoord2d( _s:Float, _t:Float ):Void;
	public static function TexCoord2f( _s:Float, _t:Float ):Void;
	public static function TexCoord2i( _s:Int, _t:Int ):Void;
	public static function TexCoord2s( _s:Int, _t:Int ):Void;
	public static function TexCoord3d( _s:Float, _t:Float, _r:Float ):Void;
	public static function TexCoord3f( _s:Float, _t:Float, _r:Float ):Void;
	public static function TexCoord3i( _s:Int, _t:Int, _r:Int ):Void;
	public static function TexCoord3s( _s:Int, _t:Int, _r:Int ):Void;
	public static function TexCoord4d( _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function TexCoord4f( _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function TexCoord4i( _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function TexCoord4s( _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function TexCoord1dv( _v:Float ):Void;
	public static function TexCoord1fv( _v:Float ):Void;
	public static function TexCoord1iv( _v:Int ):Void;
	public static function TexCoord1sv( _v:Int ):Void;
	public static function TexCoord2dv( _v:Float ):Void;
	public static function TexCoord2fv( _v:Float ):Void;
	public static function TexCoord2iv( _v:Int ):Void;
	public static function TexCoord2sv( _v:Int ):Void;
	public static function TexCoord3dv( _v:Float ):Void;
	public static function TexCoord3fv( _v:Float ):Void;
	public static function TexCoord3iv( _v:Int ):Void;
	public static function TexCoord3sv( _v:Int ):Void;
	public static function TexCoord4dv( _v:Float ):Void;
	public static function TexCoord4fv( _v:Float ):Void;
	public static function TexCoord4iv( _v:Int ):Void;
	public static function TexCoord4sv( _v:Int ):Void;
	public static function RasterPos2d( _x:Float, _y:Float ):Void;
	public static function RasterPos2f( _x:Float, _y:Float ):Void;
	public static function RasterPos2i( _x:Int, _y:Int ):Void;
	public static function RasterPos2s( _x:Int, _y:Int ):Void;
	public static function RasterPos3d( _x:Float, _y:Float, _z:Float ):Void;
	public static function RasterPos3f( _x:Float, _y:Float, _z:Float ):Void;
	public static function RasterPos3i( _x:Int, _y:Int, _z:Int ):Void;
	public static function RasterPos3s( _x:Int, _y:Int, _z:Int ):Void;
	public static function RasterPos4d( _x:Float, _y:Float, _z:Float, _w:Float ):Void;
	public static function RasterPos4f( _x:Float, _y:Float, _z:Float, _w:Float ):Void;
	public static function RasterPos4i( _x:Int, _y:Int, _z:Int, _w:Int ):Void;
	public static function RasterPos4s( _x:Int, _y:Int, _z:Int, _w:Int ):Void;
	public static function RasterPos2dv( _v:Float ):Void;
	public static function RasterPos2fv( _v:Float ):Void;
	public static function RasterPos2iv( _v:Int ):Void;
	public static function RasterPos2sv( _v:Int ):Void;
	public static function RasterPos3dv( _v:Float ):Void;
	public static function RasterPos3fv( _v:Float ):Void;
	public static function RasterPos3iv( _v:Int ):Void;
	public static function RasterPos3sv( _v:Int ):Void;
	public static function RasterPos4dv( _v:Float ):Void;
	public static function RasterPos4fv( _v:Float ):Void;
	public static function RasterPos4iv( _v:Int ):Void;
	public static function RasterPos4sv( _v:Int ):Void;
	public static function Rectd( _x1:Float, _y1:Float, _x2:Float, _y2:Float ):Void;
	public static function Rectf( _x1:Float, _y1:Float, _x2:Float, _y2:Float ):Void;
	public static function Recti( _x1:Int, _y1:Int, _x2:Int, _y2:Int ):Void;
	public static function Rects( _x1:Int, _y1:Int, _x2:Int, _y2:Int ):Void;
	public static function Rectdv( _v1:Float, _v2:Float ):Void;
	public static function Rectfv( _v1:Float, _v2:Float ):Void;
	public static function Rectiv( _v1:Int, _v2:Int ):Void;
	public static function Rectsv( _v1:Int, _v2:Int ):Void;
	public static function VertexPointer( _size:Int, _type:Int, _stride:Int, _ptr:Void ):Void;
	public static function NormalPointer( _type:Int, _stride:Int, _ptr:Void ):Void;
	public static function ColorPointer( _size:Int, _type:Int, _stride:Int, _ptr:Void ):Void;
	public static function IndexPointer( _type:Int, _stride:Int, _ptr:Void ):Void;
	public static function TexCoordPointer( _size:Int, _type:Int, _stride:Int, _ptr:Void ):Void;
	public static function EdgeFlagPointer( _stride:Int, _ptr:Void ):Void;
	public static function GetPointerv( _pname:Int, _params:Dynamic ):Void;
	public static function ArrayElement( _i:Int ):Void;
	public static function DrawArrays( _mode:Int, _first:Int, _count:Int ):Void;
	public static function DrawElements( _mode:Int, _count:Int, _type:Int, _indices:Void ):Void;
	public static function InterleavedArrays( _format:Int, _stride:Int, _pointer:Void ):Void;
	public static function ShadeModel( _mode:Int ):Void;
	public static function Lightf( _light:Int, _pname:Int, _param:Float ):Void;
	public static function Lighti( _light:Int, _pname:Int, _param:Int ):Void;
	public static function Lightfv( _light:Int, _pname:Int, _params:Float ):Void;
	public static function Lightiv( _light:Int, _pname:Int, _params:Int ):Void;
	public static function GetLightfv( _light:Int, _pname:Int, _params:Float ):Void;
	public static function GetLightiv( _light:Int, _pname:Int, _params:Int ):Void;
	public static function LightModelf( _pname:Int, _param:Float ):Void;
	public static function LightModeli( _pname:Int, _param:Int ):Void;
	public static function LightModelfv( _pname:Int, _params:Float ):Void;
	public static function LightModeliv( _pname:Int, _params:Int ):Void;
	public static function Materialf( _face:Int, _pname:Int, _param:Float ):Void;
	public static function Materiali( _face:Int, _pname:Int, _param:Int ):Void;
	public static function Materialfv( _face:Int, _pname:Int, _params:Float ):Void;
	public static function Materialiv( _face:Int, _pname:Int, _params:Int ):Void;
	public static function GetMaterialfv( _face:Int, _pname:Int, _params:Float ):Void;
	public static function GetMaterialiv( _face:Int, _pname:Int, _params:Int ):Void;
	public static function ColorMaterial( _face:Int, _mode:Int ):Void;
	public static function PixelZoom( _xfactor:Float, _yfactor:Float ):Void;
	public static function PixelStoref( _pname:Int, _param:Float ):Void;
	public static function PixelStorei( _pname:Int, _param:Int ):Void;
	public static function PixelTransferf( _pname:Int, _param:Float ):Void;
	public static function PixelTransferi( _pname:Int, _param:Int ):Void;
	public static function PixelMapfv( _map:Int, _mapsize:Int, _values:Float ):Void;
	public static function PixelMapuiv( _map:Int, _mapsize:Int, _values:Int ):Void;
	public static function PixelMapusv( _map:Int, _mapsize:Int, _values:Int ):Void;
	public static function GetPixelMapfv( _map:Int, _values:Float ):Void;
	public static function GetPixelMapuiv( _map:Int, _values:Int ):Void;
	public static function GetPixelMapusv( _map:Int, _values:Int ):Void;
	public static function Bitmap( _width:Int, _height:Int, _xorig:Float, _yorig:Float, _xmove:Float, _ymove:Float, _bitmap:String ):Void;
	public static function ReadPixels( _x:Int, _y:Int, _width:Int, _height:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function DrawPixels( _width:Int, _height:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function CopyPixels( _x:Int, _y:Int, _width:Int, _height:Int, _type:Int ):Void;
	public static function StencilFunc( _func:Int, _ref:Int, _mask:Int ):Void;
	public static function StencilMask( _mask:Int ):Void;
	public static function StencilOp( _fail:Int, _zfail:Int, _zpass:Int ):Void;
	public static function ClearStencil( _s:Int ):Void;
	public static function TexGend( _coord:Int, _pname:Int, _param:Float ):Void;
	public static function TexGenf( _coord:Int, _pname:Int, _param:Float ):Void;
	public static function TexGeni( _coord:Int, _pname:Int, _param:Int ):Void;
	public static function TexGendv( _coord:Int, _pname:Int, _params:Float ):Void;
	public static function TexGenfv( _coord:Int, _pname:Int, _params:Float ):Void;
	public static function TexGeniv( _coord:Int, _pname:Int, _params:Int ):Void;
	public static function GetTexGendv( _coord:Int, _pname:Int, _params:Float ):Void;
	public static function GetTexGenfv( _coord:Int, _pname:Int, _params:Float ):Void;
	public static function GetTexGeniv( _coord:Int, _pname:Int, _params:Int ):Void;
	public static function TexEnvf( _target:Int, _pname:Int, _param:Float ):Void;
	public static function TexEnvi( _target:Int, _pname:Int, _param:Int ):Void;
	public static function TexEnvfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function TexEnviv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function GetTexEnvfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetTexEnviv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function TexParameterf( _target:Int, _pname:Int, _param:Float ):Void;
	public static function TexParameteri( _target:Int, _pname:Int, _param:Int ):Void;
	public static function TexParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function TexParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function GetTexParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetTexParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function GetTexLevelParameterfv( _target:Int, _level:Int, _pname:Int, _params:Float ):Void;
	public static function GetTexLevelParameteriv( _target:Int, _level:Int, _pname:Int, _params:Int ):Void;
	public static function TexImage1D( _target:Int, _level:Int, _internalFormat:Int, _width:Int, _border:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function TexImage2D( _target:Int, _level:Int, _internalFormat:Int, _width:Int, _height:Int, _border:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function GetTexImage( _target:Int, _level:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function GenTextures( _n:Int, _textures:Int ):Void;
	public static function DeleteTextures( _n:Int, _textures:Int ):Void;
	public static function BindTexture( _target:Int, _texture:Int ):Void;
	public static function PrioritizeTextures( _n:Int, _textures:Int, _priorities:Float ):Void;
	public static function AreTexturesResident( _n:Int, _textures:Int, _residences:String ):Int;
	public static function IsTexture( _texture:Int ):Int;
	public static function TexSubImage1D( _target:Int, _level:Int, _xoffset:Int, _width:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function TexSubImage2D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _width:Int, _height:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function CopyTexImage1D( _target:Int, _level:Int, _internalformat:Int, _x:Int, _y:Int, _width:Int, _border:Int ):Void;
	public static function CopyTexImage2D( _target:Int, _level:Int, _internalformat:Int, _x:Int, _y:Int, _width:Int, _height:Int, _border:Int ):Void;
	public static function CopyTexSubImage1D( _target:Int, _level:Int, _xoffset:Int, _x:Int, _y:Int, _width:Int ):Void;
	public static function CopyTexSubImage2D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _x:Int, _y:Int, _width:Int, _height:Int ):Void;
	public static function Map1d( _target:Int, _u1:Float, _u2:Float, _stride:Int, _order:Int, _points:Float ):Void;
	public static function Map1f( _target:Int, _u1:Float, _u2:Float, _stride:Int, _order:Int, _points:Float ):Void;
	public static function Map2d( _target:Int, _u1:Float, _u2:Float, _ustride:Int, _uorder:Int, _v1:Float, _v2:Float, _vstride:Int, _vorder:Int, _points:Float ):Void;
	public static function Map2f( _target:Int, _u1:Float, _u2:Float, _ustride:Int, _uorder:Int, _v1:Float, _v2:Float, _vstride:Int, _vorder:Int, _points:Float ):Void;
	public static function GetMapdv( _target:Int, _query:Int, _v:Float ):Void;
	public static function GetMapfv( _target:Int, _query:Int, _v:Float ):Void;
	public static function GetMapiv( _target:Int, _query:Int, _v:Int ):Void;
	public static function EvalCoord1d( _u:Float ):Void;
	public static function EvalCoord1f( _u:Float ):Void;
	public static function EvalCoord1dv( _u:Float ):Void;
	public static function EvalCoord1fv( _u:Float ):Void;
	public static function EvalCoord2d( _u:Float, _v:Float ):Void;
	public static function EvalCoord2f( _u:Float, _v:Float ):Void;
	public static function EvalCoord2dv( _u:Float ):Void;
	public static function EvalCoord2fv( _u:Float ):Void;
	public static function MapGrid1d( _un:Int, _u1:Float, _u2:Float ):Void;
	public static function MapGrid1f( _un:Int, _u1:Float, _u2:Float ):Void;
	public static function MapGrid2d( _un:Int, _u1:Float, _u2:Float, _vn:Int, _v1:Float, _v2:Float ):Void;
	public static function MapGrid2f( _un:Int, _u1:Float, _u2:Float, _vn:Int, _v1:Float, _v2:Float ):Void;
	public static function EvalPoint1( _i:Int ):Void;
	public static function EvalPoint2( _i:Int, _j:Int ):Void;
	public static function EvalMesh1( _mode:Int, _i1:Int, _i2:Int ):Void;
	public static function EvalMesh2( _mode:Int, _i1:Int, _i2:Int, _j1:Int, _j2:Int ):Void;
	public static function Fogf( _pname:Int, _param:Float ):Void;
	public static function Fogi( _pname:Int, _param:Int ):Void;
	public static function Fogfv( _pname:Int, _params:Float ):Void;
	public static function Fogiv( _pname:Int, _params:Int ):Void;
	public static function FeedbackBuffer( _size:Int, _type:Int, _buffer:Float ):Void;
	public static function PassThrough( _token:Float ):Void;
	public static function SelectBuffer( _size:Int, _buffer:Int ):Void;
	public static function InitNames( ):Void;
	public static function LoadName( _name:Int ):Void;
	public static function PushName( _name:Int ):Void;
	public static function PopName( ):Void;
	public static var RESCALE_NORMAL:Int;
	public static var CLAMP_TO_EDGE:Int;
	public static var MAX_ELEMENTS_VERTICES:Int;
	public static var MAX_ELEMENTS_INDICES:Int;
	public static var BGR:Int;
	public static var BGRA:Int;
	public static var UNSIGNED_BYTE_3_3_2:Int;
	public static var UNSIGNED_BYTE_2_3_3_REV:Int;
	public static var UNSIGNED_SHORT_5_6_5:Int;
	public static var UNSIGNED_SHORT_5_6_5_REV:Int;
	public static var UNSIGNED_SHORT_4_4_4_4:Int;
	public static var UNSIGNED_SHORT_4_4_4_4_REV:Int;
	public static var UNSIGNED_SHORT_5_5_5_1:Int;
	public static var UNSIGNED_SHORT_1_5_5_5_REV:Int;
	public static var UNSIGNED_INT_8_8_8_8:Int;
	public static var UNSIGNED_INT_8_8_8_8_REV:Int;
	public static var UNSIGNED_INT_10_10_10_2:Int;
	public static var UNSIGNED_INT_2_10_10_10_REV:Int;
	public static var LIGHT_MODEL_COLOR_CONTROL:Int;
	public static var SINGLE_COLOR:Int;
	public static var SEPARATE_SPECULAR_COLOR:Int;
	public static var TEXTURE_MIN_LOD:Int;
	public static var TEXTURE_MAX_LOD:Int;
	public static var TEXTURE_BASE_LEVEL:Int;
	public static var TEXTURE_MAX_LEVEL:Int;
	public static var SMOOTH_POINT_SIZE_RANGE:Int;
	public static var SMOOTH_POINT_SIZE_GRANULARITY:Int;
	public static var SMOOTH_LINE_WIDTH_RANGE:Int;
	public static var SMOOTH_LINE_WIDTH_GRANULARITY:Int;
	public static var ALIASED_POINT_SIZE_RANGE:Int;
	public static var ALIASED_LINE_WIDTH_RANGE:Int;
	public static var PACK_SKIP_IMAGES:Int;
	public static var PACK_IMAGE_HEIGHT:Int;
	public static var UNPACK_SKIP_IMAGES:Int;
	public static var UNPACK_IMAGE_HEIGHT:Int;
	public static var TEXTURE_3D:Int;
	public static var PROXY_TEXTURE_3D:Int;
	public static var TEXTURE_DEPTH:Int;
	public static var TEXTURE_WRAP_R:Int;
	public static var MAX_3D_TEXTURE_SIZE:Int;
	public static var TEXTURE_BINDING_3D:Int;
	public static function DrawRangeElements( _mode:Int, _start:Int, _end:Int, _count:Int, _type:Int, _indices:Void ):Void;
	public static function TexImage3D( _target:Int, _level:Int, _internalFormat:Int, _width:Int, _height:Int, _depth:Int, _border:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function TexSubImage3D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _zoffset:Int, _width:Int, _height:Int, _depth:Int, _format:Int, _type:Int, _pixels:Void ):Void;
	public static function CopyTexSubImage3D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _zoffset:Int, _x:Int, _y:Int, _width:Int, _height:Int ):Void;
	public static var CONSTANT_COLOR:Int;
	public static var ONE_MINUS_CONSTANT_COLOR:Int;
	public static var CONSTANT_ALPHA:Int;
	public static var ONE_MINUS_CONSTANT_ALPHA:Int;
	public static var COLOR_TABLE:Int;
	public static var POST_CONVOLUTION_COLOR_TABLE:Int;
	public static var POST_COLOR_MATRIX_COLOR_TABLE:Int;
	public static var PROXY_COLOR_TABLE:Int;
	public static var PROXY_POST_CONVOLUTION_COLOR_TABLE:Int;
	public static var PROXY_POST_COLOR_MATRIX_COLOR_TABLE:Int;
	public static var COLOR_TABLE_SCALE:Int;
	public static var COLOR_TABLE_BIAS:Int;
	public static var COLOR_TABLE_FORMAT:Int;
	public static var COLOR_TABLE_WIDTH:Int;
	public static var COLOR_TABLE_RED_SIZE:Int;
	public static var COLOR_TABLE_GREEN_SIZE:Int;
	public static var COLOR_TABLE_BLUE_SIZE:Int;
	public static var COLOR_TABLE_ALPHA_SIZE:Int;
	public static var COLOR_TABLE_LUMINANCE_SIZE:Int;
	public static var COLOR_TABLE_INTENSITY_SIZE:Int;
	public static var CONVOLUTION_1D:Int;
	public static var CONVOLUTION_2D:Int;
	public static var SEPARABLE_2D:Int;
	public static var CONVOLUTION_BORDER_MODE:Int;
	public static var CONVOLUTION_FILTER_SCALE:Int;
	public static var CONVOLUTION_FILTER_BIAS:Int;
	public static var REDUCE:Int;
	public static var CONVOLUTION_FORMAT:Int;
	public static var CONVOLUTION_WIDTH:Int;
	public static var CONVOLUTION_HEIGHT:Int;
	public static var MAX_CONVOLUTION_WIDTH:Int;
	public static var MAX_CONVOLUTION_HEIGHT:Int;
	public static var POST_CONVOLUTION_RED_SCALE:Int;
	public static var POST_CONVOLUTION_GREEN_SCALE:Int;
	public static var POST_CONVOLUTION_BLUE_SCALE:Int;
	public static var POST_CONVOLUTION_ALPHA_SCALE:Int;
	public static var POST_CONVOLUTION_RED_BIAS:Int;
	public static var POST_CONVOLUTION_GREEN_BIAS:Int;
	public static var POST_CONVOLUTION_BLUE_BIAS:Int;
	public static var POST_CONVOLUTION_ALPHA_BIAS:Int;
	public static var CONSTANT_BORDER:Int;
	public static var REPLICATE_BORDER:Int;
	public static var CONVOLUTION_BORDER_COLOR:Int;
	public static var COLOR_MATRIX:Int;
	public static var COLOR_MATRIX_STACK_DEPTH:Int;
	public static var MAX_COLOR_MATRIX_STACK_DEPTH:Int;
	public static var POST_COLOR_MATRIX_RED_SCALE:Int;
	public static var POST_COLOR_MATRIX_GREEN_SCALE:Int;
	public static var POST_COLOR_MATRIX_BLUE_SCALE:Int;
	public static var POST_COLOR_MATRIX_ALPHA_SCALE:Int;
	public static var POST_COLOR_MATRIX_RED_BIAS:Int;
	public static var POST_COLOR_MATRIX_GREEN_BIAS:Int;
	public static var POST_COLOR_MATRIX_BLUE_BIAS:Int;
	public static var POST_COLOR_MATRIX_ALPHA_BIAS:Int;
	public static var HISTOGRAM:Int;
	public static var PROXY_HISTOGRAM:Int;
	public static var HISTOGRAM_WIDTH:Int;
	public static var HISTOGRAM_FORMAT:Int;
	public static var HISTOGRAM_RED_SIZE:Int;
	public static var HISTOGRAM_GREEN_SIZE:Int;
	public static var HISTOGRAM_BLUE_SIZE:Int;
	public static var HISTOGRAM_ALPHA_SIZE:Int;
	public static var HISTOGRAM_LUMINANCE_SIZE:Int;
	public static var HISTOGRAM_SINK:Int;
	public static var MINMAX:Int;
	public static var MINMAX_FORMAT:Int;
	public static var MINMAX_SINK:Int;
	public static var TABLE_TOO_LARGE:Int;
	public static var BLEND_EQUATION:Int;
	public static var MIN:Int;
	public static var MAX:Int;
	public static var FUNC_ADD:Int;
	public static var FUNC_SUBTRACT:Int;
	public static var FUNC_REVERSE_SUBTRACT:Int;
	public static var BLEND_COLOR:Int;
	public static function ColorTable( _target:Int, _internalformat:Int, _width:Int, _format:Int, _type:Int, _table:Void ):Void;
	public static function ColorSubTable( _target:Int, _start:Int, _count:Int, _format:Int, _type:Int, _data:Void ):Void;
	public static function ColorTableParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function ColorTableParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function CopyColorSubTable( _target:Int, _start:Int, _x:Int, _y:Int, _width:Int ):Void;
	public static function CopyColorTable( _target:Int, _internalformat:Int, _x:Int, _y:Int, _width:Int ):Void;
	public static function GetColorTable( _target:Int, _format:Int, _type:Int, _table:Void ):Void;
	public static function GetColorTableParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetColorTableParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function BlendEquation( _mode:Int ):Void;
	public static function BlendColor( _red:Float, _green:Float, _blue:Float, _alpha:Float ):Void;
	public static function Histogram( _target:Int, _width:Int, _internalformat:Int, _sink:Int ):Void;
	public static function ResetHistogram( _target:Int ):Void;
	public static function GetHistogram( _target:Int, _reset:Int, _format:Int, _type:Int, _values:Void ):Void;
	public static function GetHistogramParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetHistogramParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function Minmax( _target:Int, _internalformat:Int, _sink:Int ):Void;
	public static function ResetMinmax( _target:Int ):Void;
	public static function GetMinmax( _target:Int, _reset:Int, _format:Int, _types:Int, _values:Void ):Void;
	public static function GetMinmaxParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetMinmaxParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function ConvolutionFilter1D( _target:Int, _internalformat:Int, _width:Int, _format:Int, _type:Int, _image:Void ):Void;
	public static function ConvolutionFilter2D( _target:Int, _internalformat:Int, _width:Int, _height:Int, _format:Int, _type:Int, _image:Void ):Void;
	public static function ConvolutionParameterf( _target:Int, _pname:Int, _params:Float ):Void;
	public static function ConvolutionParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function ConvolutionParameteri( _target:Int, _pname:Int, _params:Int ):Void;
	public static function ConvolutionParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function CopyConvolutionFilter1D( _target:Int, _internalformat:Int, _x:Int, _y:Int, _width:Int ):Void;
	public static function CopyConvolutionFilter2D( _target:Int, _internalformat:Int, _x:Int, _y:Int, _width:Int, _height:Int ):Void;
	public static function GetConvolutionFilter( _target:Int, _format:Int, _type:Int, _image:Void ):Void;
	public static function GetConvolutionParameterfv( _target:Int, _pname:Int, _params:Float ):Void;
	public static function GetConvolutionParameteriv( _target:Int, _pname:Int, _params:Int ):Void;
	public static function SeparableFilter2D( _target:Int, _internalformat:Int, _width:Int, _height:Int, _format:Int, _type:Int, _row:Void, _column:Void ):Void;
	public static function GetSeparableFilter( _target:Int, _format:Int, _type:Int, _row:Void, _column:Void, _span:Void ):Void;
	public static var TEXTURE0:Int;
	public static var TEXTURE1:Int;
	public static var TEXTURE2:Int;
	public static var TEXTURE3:Int;
	public static var TEXTURE4:Int;
	public static var TEXTURE5:Int;
	public static var TEXTURE6:Int;
	public static var TEXTURE7:Int;
	public static var TEXTURE8:Int;
	public static var TEXTURE9:Int;
	public static var TEXTURE10:Int;
	public static var TEXTURE11:Int;
	public static var TEXTURE12:Int;
	public static var TEXTURE13:Int;
	public static var TEXTURE14:Int;
	public static var TEXTURE15:Int;
	public static var TEXTURE16:Int;
	public static var TEXTURE17:Int;
	public static var TEXTURE18:Int;
	public static var TEXTURE19:Int;
	public static var TEXTURE20:Int;
	public static var TEXTURE21:Int;
	public static var TEXTURE22:Int;
	public static var TEXTURE23:Int;
	public static var TEXTURE24:Int;
	public static var TEXTURE25:Int;
	public static var TEXTURE26:Int;
	public static var TEXTURE27:Int;
	public static var TEXTURE28:Int;
	public static var TEXTURE29:Int;
	public static var TEXTURE30:Int;
	public static var TEXTURE31:Int;
	public static var ACTIVE_TEXTURE:Int;
	public static var CLIENT_ACTIVE_TEXTURE:Int;
	public static var MAX_TEXTURE_UNITS:Int;
	public static var NORMAL_MAP:Int;
	public static var REFLECTION_MAP:Int;
	public static var TEXTURE_CUBE_MAP:Int;
	public static var TEXTURE_BINDING_CUBE_MAP:Int;
	public static var TEXTURE_CUBE_MAP_POSITIVE_X:Int;
	public static var TEXTURE_CUBE_MAP_NEGATIVE_X:Int;
	public static var TEXTURE_CUBE_MAP_POSITIVE_Y:Int;
	public static var TEXTURE_CUBE_MAP_NEGATIVE_Y:Int;
	public static var TEXTURE_CUBE_MAP_POSITIVE_Z:Int;
	public static var TEXTURE_CUBE_MAP_NEGATIVE_Z:Int;
	public static var PROXY_TEXTURE_CUBE_MAP:Int;
	public static var MAX_CUBE_MAP_TEXTURE_SIZE:Int;
	public static var COMPRESSED_ALPHA:Int;
	public static var COMPRESSED_LUMINANCE:Int;
	public static var COMPRESSED_LUMINANCE_ALPHA:Int;
	public static var COMPRESSED_INTENSITY:Int;
	public static var COMPRESSED_RGB:Int;
	public static var COMPRESSED_RGBA:Int;
	public static var TEXTURE_COMPRESSION_HINT:Int;
	public static var TEXTURE_COMPRESSED_IMAGE_SIZE:Int;
	public static var TEXTURE_COMPRESSED:Int;
	public static var NUM_COMPRESSED_TEXTURE_FORMATS:Int;
	public static var COMPRESSED_TEXTURE_FORMATS:Int;
	public static var MULTISAMPLE:Int;
	public static var SAMPLE_ALPHA_TO_COVERAGE:Int;
	public static var SAMPLE_ALPHA_TO_ONE:Int;
	public static var SAMPLE_COVERAGE:Int;
	public static var SAMPLE_BUFFERS:Int;
	public static var SAMPLES:Int;
	public static var SAMPLE_COVERAGE_VALUE:Int;
	public static var SAMPLE_COVERAGE_INVERT:Int;
	public static var MULTISAMPLE_BIT:Int;
	public static var TRANSPOSE_MODELVIEW_MATRIX:Int;
	public static var TRANSPOSE_PROJECTION_MATRIX:Int;
	public static var TRANSPOSE_TEXTURE_MATRIX:Int;
	public static var TRANSPOSE_COLOR_MATRIX:Int;
	public static var COMBINE:Int;
	public static var COMBINE_RGB:Int;
	public static var COMBINE_ALPHA:Int;
	public static var SOURCE0_RGB:Int;
	public static var SOURCE1_RGB:Int;
	public static var SOURCE2_RGB:Int;
	public static var SOURCE0_ALPHA:Int;
	public static var SOURCE1_ALPHA:Int;
	public static var SOURCE2_ALPHA:Int;
	public static var OPERAND0_RGB:Int;
	public static var OPERAND1_RGB:Int;
	public static var OPERAND2_RGB:Int;
	public static var OPERAND0_ALPHA:Int;
	public static var OPERAND1_ALPHA:Int;
	public static var OPERAND2_ALPHA:Int;
	public static var RGB_SCALE:Int;
	public static var ADD_SIGNED:Int;
	public static var INTERPOLATE:Int;
	public static var SUBTRACT:Int;
	public static var CONSTANT:Int;
	public static var PRIMARY_COLOR:Int;
	public static var PREVIOUS:Int;
	public static var DOT3_RGB:Int;
	public static var DOT3_RGBA:Int;
	public static var CLAMP_TO_BORDER:Int;
	public static function ActiveTexture( _texture:Int ):Void;
	public static function ClientActiveTexture( _texture:Int ):Void;
	public static function CompressedTexImage1D( _target:Int, _level:Int, _internalformat:Int, _width:Int, _border:Int, _imageSize:Int, _data:Void ):Void;
	public static function CompressedTexImage2D( _target:Int, _level:Int, _internalformat:Int, _width:Int, _height:Int, _border:Int, _imageSize:Int, _data:Void ):Void;
	public static function CompressedTexImage3D( _target:Int, _level:Int, _internalformat:Int, _width:Int, _height:Int, _depth:Int, _border:Int, _imageSize:Int, _data:Void ):Void;
	public static function CompressedTexSubImage1D( _target:Int, _level:Int, _xoffset:Int, _width:Int, _format:Int, _imageSize:Int, _data:Void ):Void;
	public static function CompressedTexSubImage2D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _width:Int, _height:Int, _format:Int, _imageSize:Int, _data:Void ):Void;
	public static function CompressedTexSubImage3D( _target:Int, _level:Int, _xoffset:Int, _yoffset:Int, _zoffset:Int, _width:Int, _height:Int, _depth:Int, _format:Int, _imageSize:Int, _data:Void ):Void;
	public static function GetCompressedTexImage( _target:Int, _lod:Int, _img:Void ):Void;
	public static function MultiTexCoord1d( _target:Int, _s:Float ):Void;
	public static function MultiTexCoord1dv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord1f( _target:Int, _s:Float ):Void;
	public static function MultiTexCoord1fv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord1i( _target:Int, _s:Int ):Void;
	public static function MultiTexCoord1iv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord1s( _target:Int, _s:Int ):Void;
	public static function MultiTexCoord1sv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord2d( _target:Int, _s:Float, _t:Float ):Void;
	public static function MultiTexCoord2dv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord2f( _target:Int, _s:Float, _t:Float ):Void;
	public static function MultiTexCoord2fv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord2i( _target:Int, _s:Int, _t:Int ):Void;
	public static function MultiTexCoord2iv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord2s( _target:Int, _s:Int, _t:Int ):Void;
	public static function MultiTexCoord2sv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord3d( _target:Int, _s:Float, _t:Float, _r:Float ):Void;
	public static function MultiTexCoord3dv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord3f( _target:Int, _s:Float, _t:Float, _r:Float ):Void;
	public static function MultiTexCoord3fv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord3i( _target:Int, _s:Int, _t:Int, _r:Int ):Void;
	public static function MultiTexCoord3iv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord3s( _target:Int, _s:Int, _t:Int, _r:Int ):Void;
	public static function MultiTexCoord3sv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord4d( _target:Int, _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function MultiTexCoord4dv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord4f( _target:Int, _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function MultiTexCoord4fv( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord4i( _target:Int, _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function MultiTexCoord4iv( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord4s( _target:Int, _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function MultiTexCoord4sv( _target:Int, _v:Int ):Void;
	public static function LoadTransposeMatrixd( _m:Float ):Void;
	public static function LoadTransposeMatrixf( _m:Float ):Void;
	public static function MultTransposeMatrixd( _m:Float ):Void;
	public static function MultTransposeMatrixf( _m:Float ):Void;
	public static function SampleCoverage( _value:Float, _invert:Int ):Void;
	public static var ARB_multitexture:Int;
	public static var TEXTURE0_ARB:Int;
	public static var TEXTURE1_ARB:Int;
	public static var TEXTURE2_ARB:Int;
	public static var TEXTURE3_ARB:Int;
	public static var TEXTURE4_ARB:Int;
	public static var TEXTURE5_ARB:Int;
	public static var TEXTURE6_ARB:Int;
	public static var TEXTURE7_ARB:Int;
	public static var TEXTURE8_ARB:Int;
	public static var TEXTURE9_ARB:Int;
	public static var TEXTURE10_ARB:Int;
	public static var TEXTURE11_ARB:Int;
	public static var TEXTURE12_ARB:Int;
	public static var TEXTURE13_ARB:Int;
	public static var TEXTURE14_ARB:Int;
	public static var TEXTURE15_ARB:Int;
	public static var TEXTURE16_ARB:Int;
	public static var TEXTURE17_ARB:Int;
	public static var TEXTURE18_ARB:Int;
	public static var TEXTURE19_ARB:Int;
	public static var TEXTURE20_ARB:Int;
	public static var TEXTURE21_ARB:Int;
	public static var TEXTURE22_ARB:Int;
	public static var TEXTURE23_ARB:Int;
	public static var TEXTURE24_ARB:Int;
	public static var TEXTURE25_ARB:Int;
	public static var TEXTURE26_ARB:Int;
	public static var TEXTURE27_ARB:Int;
	public static var TEXTURE28_ARB:Int;
	public static var TEXTURE29_ARB:Int;
	public static var TEXTURE30_ARB:Int;
	public static var TEXTURE31_ARB:Int;
	public static var ACTIVE_TEXTURE_ARB:Int;
	public static var CLIENT_ACTIVE_TEXTURE_ARB:Int;
	public static var MAX_TEXTURE_UNITS_ARB:Int;
	public static function ActiveTextureARB( _texture:Int ):Void;
	public static function ClientActiveTextureARB( _texture:Int ):Void;
	public static function MultiTexCoord1dARB( _target:Int, _s:Float ):Void;
	public static function MultiTexCoord1dvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord1fARB( _target:Int, _s:Float ):Void;
	public static function MultiTexCoord1fvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord1iARB( _target:Int, _s:Int ):Void;
	public static function MultiTexCoord1ivARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord1sARB( _target:Int, _s:Int ):Void;
	public static function MultiTexCoord1svARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord2dARB( _target:Int, _s:Float, _t:Float ):Void;
	public static function MultiTexCoord2dvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord2fARB( _target:Int, _s:Float, _t:Float ):Void;
	public static function MultiTexCoord2fvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord2iARB( _target:Int, _s:Int, _t:Int ):Void;
	public static function MultiTexCoord2ivARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord2sARB( _target:Int, _s:Int, _t:Int ):Void;
	public static function MultiTexCoord2svARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord3dARB( _target:Int, _s:Float, _t:Float, _r:Float ):Void;
	public static function MultiTexCoord3dvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord3fARB( _target:Int, _s:Float, _t:Float, _r:Float ):Void;
	public static function MultiTexCoord3fvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord3iARB( _target:Int, _s:Int, _t:Int, _r:Int ):Void;
	public static function MultiTexCoord3ivARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord3sARB( _target:Int, _s:Int, _t:Int, _r:Int ):Void;
	public static function MultiTexCoord3svARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord4dARB( _target:Int, _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function MultiTexCoord4dvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord4fARB( _target:Int, _s:Float, _t:Float, _r:Float, _q:Float ):Void;
	public static function MultiTexCoord4fvARB( _target:Int, _v:Float ):Void;
	public static function MultiTexCoord4iARB( _target:Int, _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function MultiTexCoord4ivARB( _target:Int, _v:Int ):Void;
	public static function MultiTexCoord4sARB( _target:Int, _s:Int, _t:Int, _r:Int, _q:Int ):Void;
	public static function MultiTexCoord4svARB( _target:Int, _v:Int ):Void;
	public static function Map1d_01( _target:Int, _stride:Int, _order:Int, _points:Float ):Void;
	public static function CreateTexture( _tex:Int, _width:Int, _height:Int ):Int;
	public static function TexSubImage2D_BGRA_BYTE( _tex:Int, _pos:Dynamic, _size:Dynamic, _data:Dynamic ):Void;
	public static function TexSubImage2D_BGR_BYTE( _tex:Int, _pos:Dynamic, _size:Dynamic, _data:Dynamic ):Void;
	public static function TexSubImage2D_RGBA_BYTE( _tex:Int, _pos:Dynamic, _size:Dynamic, _data:Dynamic ):Void;
	public static function TexSubImage2D_RGB_BYTE( _tex:Int, _pos:Dynamic, _size:Dynamic, _data:Dynamic ):Void;
	public static function TexSubImage2D_BGRA_BYTE_PART( _tex:Int, _pos:Dynamic, _size:Dynamic, _data:Dynamic, _img_width:Dynamic ):Void;

    public static function __init__() : Void {
        untyped {
        	var loader = untyped __dollar__loader;
            GL = loader.loadmodule("GL__".__s,loader).GL__;
        }
    }
}
